services:
  nextjs:
    container_name: nextjs_homepage_homepage
    image: loadlinkdocker/loadlink-homepage:homepage
    env_file:
      - .env.homepage
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
